### PR TITLE
[WIP] Complete Revamp of HQ Trivia Master

### PR DESCRIPTION
**Pull request by schlossm**
Hi Daniel,

My friend found this app and wanted to use it for HQ.  He shared it with me to get some help to get it working for him.

As I was helping, I found a lot of code that wasn't used, had no endpoints, or otherwise was extra code.

I decided to rewrite much of the application to give it an updated look and feel, as well as a much condensed function set. Let me know what you think

# New Features
* Vastly reduced codebase by removing tons of code that was unused.  This includes code that led nowhere, wasn't connected, or otherwise was needed as smaller code was able to replace it.  There was a lot of function calls bouncing around all over the place.  They've been significantly reduced and simplified, as well as converting many functions into variables/extensions
* Updated UI.  The User Interface has been vastly updated.  The left side of the window has been removed (along with that midway centered line)
    * Defining boundary: The user is able to define a region of screen space they'd like the application to track.
    * Automated screenshotting: Using the user-defined boundary, the application is able to automatically take screenshots at certain intervals so all the user has to do is tell the app where to "see" the questions come up and the app takes care of the rest
    * Reset/Manual: The user can now reset and clear everything immediately, start/stop scanning on whim, and redefine the boundary at anytime.
* Safer code.  I have added a million and a half guard statements everywhere, with failsafes and catches to update UI as needed.  Due to the safer code, the screenshotting was able to be automated, with intervals automatically changing if an HQ question was found in the screenshot
* New classes, structs, & more.  I have implemented new classes and structs to help clean up the codebase and make the application much easier to understand.  Examples include: SiteEncoding - a struct that defines which sites the application can reach, and how their URL is formed.  AnswerCounts - a struct that allows for extremely verbose answer counting.
* Comments.  I have commented most of the application, which should make it significantly easier to follow and understand
* Sandboxing.  While the application cannot have the Sandbox Entitlement due to it's access to the terminal, I did move all generated files into the user's temporary directory to not spam their desktop, and to not require access to potentially sensitive information

[Video Demo](https://www.icloud.com/iclouddrive/047Mo7r6bWhlYmOFa5Fh1FCPw#HQ) of the updated application in action.

I understand this is a massive PR with even more massive changes; this app has great potential.  Thank you for building it, and I'm very thankful it exists

## TODO List
* Move from Tesseract to SwiftOCR
* Finish commenting more confusing parts

### CODE REVIEW

**Comment by DanielSmith1239** [comment]
The video looks awesome, and I’ll try it out soon. I really wish I had more time to work on this, but between school and other classes it’s difficult to find time.

**Comment by schlossm** [comment]
Hey it's absolutely no problem man! I remember what that was like.  I'll just keep chipping away at things I find

**Comment by DanielSmith1239** [comment]
If I merge your version into the git (which I probably will), I’m also going to help update it.

**Comment by DanielSmith1239** [comment]
Just to let you know, I was fully aware that the code needed a ton of work. There was just code that I didn’t have time to finish up or remove. I also had all of the files load on the desktop because I wanted to see the files that it was generating, I didn’t really intend for this to be used by other people.

**Pull request merged**
