### PR TITLE
[DO NOT MERGE] Added support for macOS 10.12

### PR DESCRIPTION
**Pull request by schlossm**
I also hopefully fixed the NSWindow error some are experiencing.  Need to do some more testing on that before merging

### CODE REVIEW

**Comment by DanielSmith1239** [comment]
Ok, let me know when to merge.

**Comment by kokirikat** [comment]
So how do I download this 10.12 version -- sorry, I'm new to github.

**Comment by schlossm** [comment]
[Download schlossm:master](https://github.com/schlossm/HQTriviaMaster/archive/master.zip)

**Comment by kokirikat** [comment]
I get a lot of errors with this version:/ do you want output?

**Comment by schlossm** [comment]
Go for it I don't get any errors when building

**Comment by kokirikat** [comment]
Building works perfectly -- when I started scanning the boundary, this is the output and the app auto-switches back to xcode: https://pastebin.com/DsLWHWyg.

**Comment by schlossm** [comment]
@kokirikat, you can try downloading it again.  Hasty coding and the way macOS does local device URLS got in the way

**Comment by kokirikat** [comment]
Can i get the download link please:/

**Comment by schlossm** [comment]
[Download schlossm:master](https://github.com/schlossm/HQTriviaMaster/archive/master.zip)

**Comment by DanielSmith1239** [comment]
So I’m good to merge?

**Comment by schlossm** [comment]
If @kokirikat gives a green light, yea.  I don't have 10.12 on any of my Macs so I can't test it on that OS

**Comment by kokirikat** [comment]
Runs great now, just a little inaccurate sometimes but I don't think that's a result of this update. Good work!

**Pull request merged**
